apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: jenkinsdata 
spec: 
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfsshare/jenkins
    server: master1.tdqcvioqd12ublntczh0psfdag.fx.internal.cloudapp.net  
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: jenkins
    namespace: ci

